image:
  repository: <your-aws-account-id>.dkr.ecr.eu-north-1.amazonaws.com/django-app
  tag: latest

replicaCount: 2

service:
  type: LoadBalancer
  port: 80

env:
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: pass9764gd

  