apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  POSTGRES_HOST: <rds-endpoint>
  POSTGRES_PORT: "5432"
  POSTGRES_USER: django_user
  POSTGRES_PASSWORD: pass9764gd
  POSTGRES_DB: django_db
