apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: 146554952179.dkr.ecr.eu-north-1.amazonaws.com/django-app:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-config
