apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}
